### ISSUE TITLE
Procurar Sensores de Umidade

### ISSUE THREAD

**Issue by Marcelocs19** [trabalho-sensores-de-umidade/SensoresDeUmidade#2]

**Comment by leticia1404** [comment]
https://produto.mercadolivre.com.br/MLB-981237618-sensor-de-temperatura-e-umidade-webwifiemail-smsligaco-_JM?quantity=1

**Comment by leticia1404** [comment]
Encontrado exemplo de sensores e adicionados na wiki (Sensores).
